### ISSUE TITLE
add 'which' command to basic tutorial

### ISSUE THREAD

**Issue by kdubois** [redhat-scholars/linux-tutorial#8]

**Comment by Foxymortel** [comment]
Hello, I would like to know a bit more about your purpose with the 'which' command, can you explain? I would be happy to contribute to your issue.

**Comment by kdubois** [comment]
Hi @Foxymortel !  We just want to add a "Using which" section to the Basic commands page (https://github.com/redhat-scholars/linux-tutorial/edit/master/documentation/modules/ROOT/pages/03-basic-commands.adoc).   So just a description of what the command does and a code block just like eg. the "Using whatis" section.

**Comment by cedricclyburn** [comment]
Sweet, thanks for the addition! @Foxymortel
